intro.html
South Hampton Assessment Procedure -> Southampton Hand Assessment Procedure
=> Correct a small typo

index.html, robot.html
The links are valid as soon as the actual exercises PR comes through.
=> Added exercises to Chapter 2

manipulation/exercises/pick/BUILD.bazel, manipulation/exercises/pick/test_simple_qp.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/22)
=> Simple QP Problem test code 

drake.html, scripts/setup/ubuntu/18.04/install_prereqs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/23)
=> pip install requirements in CI, but not in install_prereqs.sh

manipulation/exercises/pick/BUILD.bazel, manipulation/exercises/pick/plot_planar_manipulator.py, manipulation/exercises/pick/test_planar_manipulator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/24)
=> test and plotting files for planar manipulator

manipulation/exercises/pick/BUILD.bazel
Sorry about the missing bazel file! I had the line but it must have got deleted when I was checking out to a new branch. 
I think it's cleaner to PR this separately from the set PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/27)
=> bazel test file for diffik added

manipulation/exercises/pick/BUILD.bazel, manipulation/exercises/pick/test_rigid_transforms.py, manipulation/exercises/pick/test_robot_painter.py
Test files for robot painter and simple rigid transforms from the pset 2 drafts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/29)
=> Pick and place/painter test

pick.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/31)
=> set announcements

pick.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/32)
=> fix to broken ipynb link

exercises/pick/rigid_transforms.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/34)
=> fix typo in rigid transforms problem

exercises/pick/planar_manipulator.ipynb, exercises/robot/manipulation_station_io.ipynb, exercises/robot/reflected_inertia.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/33)
=> remove survey from reflected inertia problem

exercises/pick/differential_ik_optimization.ipynb
Part 2 of the PR, includes the notebook files! 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/36)
=> SnoptSolver for DiffIK

exercises/pick/robot_painter.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/39)
=> updated hash for painter problem

exercises/pick/differential_ik_optimization.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/40)
=> Change hash for problem 3.9

chapters.json, index.html, pose.html
Also adds better ref / derivation for the improper rotation matrix (det(R)=-1) case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/41)
=> Reflow pose chapter.

exercises/pose/BUILD.bazel, exercises/pose/bunny_icp.ipynb, exercises/pose/pose_estimation_icp.ipynb, exercises/pose/ransac.ipynb, manipulation/exercises/pose/BUILD.bazel, manipulation/exercises/pose/test_pose_estimation.py, manipulation/exercises/pose/test_ransac.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/45)
=> notebook commits for set 4

exercises/pose/bunny_icp.ipynb
Get rid of intiial_guess as one of the args in docstring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/46)
=> comment fix for bunny icp

exercises/pose/bunny_icp.ipynb, exercises/pose/pose_estimation_icp.ipynb, exercises/pose/ransac.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/49)
=> hash code changes to chapter 4 exercises

exercises/pick/differential_ik_optimization.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/53)
=> running as notebook guard in problem 3.9

BUILD.bazel, exercises/pick/BUILD.bazel, exercises/pose/BUILD.bazel, exercises/robot/BUILD.bazel, figures/BUILD.bazel, lectures/BUILD.bazel, manipulation/BUILD.bazel, manipulation/exercises/BUILD.bazel, manipulation/exercises/grader.py, manipulation/exercises/pick/BUILD.bazel, manipulation/exercises/pick/plot_planar_manipulator.py, manipulation/exercises/pick/test_robot_painter.py, manipulation/exercises/pose/BUILD.bazel, manipulation/exercises/pose/test_icp.py, manipulation/exercises/pose/test_ransac.py, manipulation/exercises/robot/BUILD.bazel, manipulation/jupyter_widgets.py, manipulation/open3d/BUILD.bazel, manipulation/open3d/show_pointcloud.py, manipulation/open3d/show_rgbd.py, scripts/setup/setup_manipulation_colab.py, setup.cfg
We will need to make the same changes to underactuated and fix up htmlbook. Closes #54.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/55)
=> Tweak linter configurations to closer match drake

manipulation/exercises/pose/test_icp.py, manipulation/exercises/pose/test_ransac.py
Doing tests first, will change hash and PR exercises next.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/57)
=> get rid of sklearn dependencies in tests

exercises/pose/bunny_icp.ipynb, exercises/pose/pose_estimation_icp.ipynb, exercises/pose/ransac.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/58)
=> get rid of sklearn from exercises

requirements.txt, scripts/setup/ubuntu/18.04/install_prereqs.sh
resolves #47
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/59)
=> remove scipy and scikit-learn

manipulation/exercises/clutter/test_analytic_grasp.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/64)
=> lower tolerance on analytic test

manipulation/exercises/clutter/test_analytic_grasp.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/66)
=> 5.1 reduce tolerance on Hessian

exercises/clutter/BUILD.bazel, exercises/clutter/analytic_antipodal_grasps.ipynb, exercises/clutter/grasp_candidate.ipynb, exercises/clutter/normal_estimation_depth.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/65)
=> Chapter 5 exercises

clutter.html, index.html
Do not merge until everything is ready for release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/63)
=> set announcement

exercises/clutter/BUILD.bazel
Add it back in once #67 is resolved.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/68)
=> temporarily leave out grasp_candidates from bazel

exercises/clutter/analytic_antipodal_grasps.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/69)
=> fix small typo in antipodal problem

exercises/clutter/analytic_antipodal_grasps.ipynb, exercises/clutter/grasp_candidate.ipynb, exercises/clutter/normal_estimation_depth.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/71)
=> update exercise hash for chapter 5

exercises/clutter/analytic_antipodal_grasps.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/72)
=> change k value in antipodal grasp problem

manipulation/exercises/clutter/test_grasp_candidate.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/73)
=> change test code for eigenvalue ordering

exercises/clutter/analytic_antipodal_grasps.ipynb, exercises/clutter/grasp_candidate.ipynb, exercises/clutter/normal_estimation_depth.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/74)
=> change hash for chapter 5 problems

exercises/clutter/grasp_candidate.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/76)
=> 5.3 notebook fix to robust handling of improper rotations

exercises/clutter/normal_estimation_depth.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/78)
=> change hash for normal problem

requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/79)
=> Change open3d version dependency

exercises/clutter/analytic_antipodal_grasps.ipynb, exercises/clutter/grasp_candidate.ipynb, exercises/clutter/normal_estimation_depth.ipynb, exercises/pose/bunny_icp.ipynb, exercises/pose/pose_estimation_icp.ipynb, exercises/pose/ransac.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/81)
=> hash bump up for notebooks with open3d dep

exercises/force/BUILD.bazel, exercises/force/hybrid_force_position.ipynb, exercises/segmentation/BUILD.bazel, exercises/segmentation/label_generation.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/86)
=> set 4 notebooks

manipulation/exercises/force/test_hybrid.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/87)
=> longer timeout for hybrid force position problem

force.html, index.html, segmentation.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/89)
=> set 4 announcement

force.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/92)
=> typo fix for problems

.github/workflows/main.yml, requirements.txt, scripts/setup/mac/Brewfile, scripts/setup/ubuntu/18.04/install_prereqs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/94)
=> attempt to fix ubuntu and mac CI

manipulation/exercises/trajectories/BUILD.bazel, manipulation/exercises/trajectories/test_door_opening.py, manipulation/exercises/trajectories/test_rrt_planning.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/97)
=> test files for set 5

exercises/trajectories/door_opening.ipynb, exercises/trajectories/rrt_planning.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/101)
=> change hash on exercises

index.html, trajectories.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/102)
=> problem announcement

chapters.json, drake.html, index.html, rl.html, trajectories.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/108)
=> Add RL Chapter

manipulation/exercises/rl/BUILD.bazel, manipulation/exercises/rl/test_stochastic_optimization.py, manipulation/exercises/rl/test_vpg.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/109)
=> set 6 tests

exercises/rl/policy_gradient.ipynb, exercises/rl/stochastic_optimization.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/112)
=> hash updates

scripts/setup/setup_manipulation_colab.py, scripts/setup/ubuntu/18.04/install_prereqs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/115)
=> subprocess will print stderr to console, and assert if the subprocess fails

exercises/rl/stochastic_optimization.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/116)
=> typo fix for notebook

manipulation/exercises/rl/test_vpg.py
fix advantage function grader
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/117)
=> fix advantage function grader

manipulation/exercises/rl/test_vpg.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/118)
=> fix vpg grader

manipulation/scenarios.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/120)
=> switch python manipstation to better gripper

drake.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/124)
=> trying to resolve mac ci

exercises/robot/reflected_inertia.ipynb, intro.html, intro.ipynb, manipulation/meshcat_cpp_utils.py, robot.html, robot.ipynb, setup/docker/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/156)
=> Robot deepnote

drake.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/159)
=> Small fix: add missing single quote

pick.html
The *only* changes are fixing the whitespace, and adding one paragraph, starting with "Take a minute to convince yourself ..."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/161)
=> touchup slerp

pose.html
Very small modification to break it into 2 parts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/163)
=> Modify 4.1 into a homework problem

lectures/qp_diff_ik.ipynb, manipulation/meshcat_cpp_utils.py
Do not merge until https://github.com/robotlocomotion/drake/pull/16077 lands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/181)
=> upgrades qp_diff_ik example to the c++ meshcat

exercises/rl/policy_gradient.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/184)
=> Fix formula for (c) on policy gradient

manipulation/exercises/robot/BUILD.bazel, manipulation/exercises/robot/test_direct_joint_control.py
test for new notebook problem
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/190)
=> pset 1 commits

robot.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/192)
=> add exercise 2.3

robot.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/193)
=> simplify exercise 2.3 (part a/b to just a)

intro.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/195)
=> Fixed minor gramatical typo in intro.html

exercises/pick/planar_manipulator.ipynb, exercises/pick/rigid_transforms.ipynb, exercises/robot/reflected_inertia.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/197)
=> changes for pset 2

pick.html
See https://piazza.com/class/l6s8p2f23ij7bz/post/126
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/200)
=> fix typo in 3.12

exercises/pose/bunny_icp.ipynb, manipulation/exercises/pose/test_icp.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/202)
=> improve numerics of test for bunny_icp

manipulation/exercises/clutter/test_grasp_candidate.py
related to https://github.com/RobotLocomotion/drake/issues/18054
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/203)
=> relax tolerance on Darboux frame test.

pose.html
Small updates based on the reflection last year.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/204)
=> update based on reflection

exercises/clutter/normal_estimation_depth.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/205)
=> fix flipped u and v in normal estimation

manipulation/exercises/clutter/test_simulation_tuning.py
[x, z] contact position check (instead of [x, y, z]) and normalize force vecs for angle computation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/210)
=> fix sim tuning tests 

exercises/deep_perception/contrastive.ipynb, manipulation/exercises/deep_perception/BUILD.bazel, manipulation/exercises/deep_perception/test_contrastive.py
add don contrastive exercise for deep perception
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/211)
=> add don contrastive exercise

deep_perception.html, index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/213)
=> add new problem to textbook

manipulation/exercises/trajectories/test_taskspace_iris.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/221)
=> update iris test to handle hyperplanes in different order

force.html
I still need to fix the image for 9.2 but want to make sure this notation looks okay before I do that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/222)
=> First pass at changing notation for 9.1 and 9.2

exercises/force/hybrid_force_position.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/225)
=> fix 9.3 force notation

exercises/rl/policy_gradient.ipynb, exercises/rl/stochastic_optimization.ipynb
The original notebook will throw an error on deepnote (but not in test). This PR fixes it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/227)
=> fix bug in pset 10 notebook

robot/exercises/02_manipulation_station_io.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/243)
=> Fix an indentation error that causes problems with the autograder for problem 2.2.

robot/exercises/02_hardware_station_io.ipynb
It broke again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/244)
=> Redo the fix from #243.

pose.html
Clarify wording of 4.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/252)
=> Clarify wording of 4.1

clutter/exercises/simulation_tuning.ipynb
+@RussTedrake for feature review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/260)
=> Run the autograder for the simulator tuning exercise.

force.html
Small wording changes to 8.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/261)
=> Small wording changes to 8.2

mobile.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/264)
=> Add Pset #7 problems to the chapter

manipulation/models/spot/spot_with_arm.urdf, manipulation/models/spot/spot_with_arm_and_floating_base_actuators.urdf, mobile/spot.ipynb
Update the Spot urdf and remote asset to the most recent version that features an update texture map for both the base and the arm.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/273)
=> Convert spot visual geometries to obj

.pre-commit-config.yaml, poetry.lock, pyproject.toml
Also adds sync between versions in pre-commit and pyproject
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/276)
=> Add pre-commit as poetry dependency

.github/workflows/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/277)
=> Add cli linting

.github/workflows/main.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/279)
=> CI: Test poetry install

.github/workflows/noncritical.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/281)
=> Separate non-critical tests on CI.

book/misc.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/288)
=> Fix a broken link to the fall 2022 project playlist.

book/pick/exercises/09_intro_to_qp.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/287)
=> Fix typo in QP exercise.

.github/workflows/main.yml, .pre-commit-config.yaml
As per title and slack discussion
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/289)
=> Github action: Peg black/isort versions, enable black jupyter, and add autoflake

book/clutter.html, book/clutter/exercises/normal_estimation_depth.ipynb, book/pick/exercises/05_planar_manipulator.ipynb, book/pick/exercises/09_intro_to_qp.ipynb, book/pose.html, book/pose/exercises/pose_estimation_icp.ipynb, book/robot/exercises/02_hardware_station_io.ipynb, book/trajectories.html, book/trajectories/exercises/door_opening.ipynb, book/trajectories/exercises/taskspace_iris.ipynb
These are more trivial suggestions that should be quick to review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/320)
=> Typos I found

book/pick/exercises/09_intro_to_qp.ipynb, book/pick/exercises/10_differential_ik_optimization.ipynb, book/pose/exercises/bunny_icp.ipynb, book/robot/simulation.ipynb, book/segmentation.html, book/segmentation/exercises/segmentation_and_grasp.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/326)
=> Fix notebook deadlinks

book/robot/exercises/03_direct_joint_control.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/328)
=> Clarify direct joint control problem

book/pick.html
I changed the numbers of the problem and slightly expanded part b). The goal was to mostly keep the question the same, but change it enough to not be an exact copy from previous years.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/330)
=> Proposed changes to 3.6

book/robot/exercises/01_reflected_inertia.ipynb
See the associated manipulation-solutions PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/335)
=> Fix display issue with reflected inertia when autograding

book/clutter/exercises/BUILD.bazel, book/pose/exercises/BUILD.bazel, book/segmentation/BUILD.bazel, book/segmentation/exercises/BUILD.bazel
Blocked by https://github.com/RussTedrake/htmlbook/pull/14 as need to merge that first and then update the subrepo.
Also blocked by the solutions PR: https://github.com/RobotLocomotion/manipulation-solutions/pull/73
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/333)
=> Fix VTK local ubuntu tests

book/force.html, book/mobile.html, book/segmentation/exercises/segmentation_and_grasp.ipynb
Found a few more typos. Thanks for making this course so accessible!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/337)
=> Jake typos 2

book/pick/exercises/08_robot_painter.ipynb, manipulation/exercises/pick/test_robot_painter.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/336)
=> Updating 3.8 Robot Painter Notebook

book/pick/pick.ipynb
Addresses the issue observed [here](https://piazza.com/class/lzpl33q13fp4qv/post/23).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/338)
=> Enable visualization while recording in pick notebook

book/pick.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/340)
=> Update typo in 3.6a

book/pick/exercises/08_robot_painter.ipynb
The previous problems didn't feel super valuable in teaching what the controller is actually doing, and some of the details were too subtle.
I replaced them with 3 new small questions. See the associated solutions PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/342)
=> rework 3.8 written problems

.github/workflows/main.yml, setup/mac/install_prereqs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/346)
=> resolve warnings on github actions

pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/347)
=> Roll new pip wheel

book/pick.html
- add hint on unit vector 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/352)
=> add hint to rotation problem

book/pose.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/354)
=> fix 4.5 prescript display

book/trajectories.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/356)
=> Fix reference

manipulation/exercises/clutter/test_grasp_candidate.py
Deepnote seems to time out on this problem, not sure why
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/361)
=> increase 5.4b time limit

book/clutter/exercises/normal_estimation_depth.ipynb
Solution PR: https://github.com/RobotLocomotion/manipulation-solutions/pull/91
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/362)
=> Clarify problem 5.2 a

book/trajectories/exercises/door_opening.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/364)
=> 6.1 Clarifying text

book/clutter.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/373)
=> 5.5 Btree clarification

manipulation/exercises/segmentation/test_segmentation_and_grasp.py
NOTE: We need to update the contained submodule after merging [this](https://github.com/RussTedrake/manipulation-data/pull/6)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/376)
=> Fix segmentation_and_grasp grader

manipulation/exercises/segmentation/BUILD.bazel, manipulation/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/377)
=> don't download a data file from inside a bazel test

.github/workflows/noncritical.yml, BUILD.bazel, Developers.md, manipulation/utils.py, pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/381)
=> allow passing MANIPULATION_DATA_DIR as an environment variable

book/rl/exercises/policy_gradient.ipynb, book/rl/exercises/stochastic_optimization.ipynb, book/trajectories.html, manipulation/exercises/rl/test_stochastic_optimization.py, manipulation/exercises/rl/test_vpg.py
* fix for REINFORCE autograder to make rewards.shape[1] == max_episode_length
* minor changes in write-up and notation
* addition of a small written question for gradient descent
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/382)
=> Tweaks for PSET 10

book/rl/exercises/stochastic_optimization.ipynb, manipulation/exercises/rl/test_stochastic_optimization.py
Changing grading as half points are not supported
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/383)
=> Fixing autograder marking

Developers.md, manipulation/station.py, poetry.lock, pyproject.toml, requirements-bazel-linux.txt, requirements-bazel-mac.txt, requirements-bazel.txt, requirements.txt
Resolves https://github.com/Learning-and-Intelligent-Systems/QR/issues/133. Depends on https://github.com/RobotLocomotion/drake/pull/22356.
fyi @siddancha
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/391)
=> Fix InverseDynamicsController actuation wiring

.github/workflows/main.yml, poetry.lock, pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/400)
=> Update pip wheels for version with extras

.github/workflows/main.yml, poetry.lock, pyproject.toml
Towards https://github.com/RussTedrake/underactuated/issues/569.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/401)
=> Remove 'test' as an extra by allowing pip workflows to exclude htmlbook tests

README.md
The link no longer works as the file was moved to a different repo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/402)
=> Fix Developers.md link

.github/workflows/main.yml, manipulation/create_sdf_from_mesh.py, manipulation/test/test_create_sdf_from_mesh.py, manipulation/test/test_gym.py
Depends on https://github.com/RussTedrake/htmlbook/pull/16. Need to merge that first and then update the submodule.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/404)
=> Add core pip ci

poetry.lock, pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/409)
=> don't include _static subdir in pip wheels

manipulation/make_drake_compatible_model.py, manipulation/test/models/test.xml, manipulation/test/test_make_drake_compatible_model.py
@nepfaff -- would you like to review this one?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/413)
=> Add workaround for Drake 19263 to make_drake_compatible_model

book/robot/inspector.ipynb, manipulation/make_drake_compatible_model.py, manipulation/test/test_make_drake_compatible_model.py, manipulation/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/415)
=> Add a test for running make_drake_compatible_model on all menagerie xmls

book/robot/BUILD.bazel, book/robot/gymnasium_robotics.ipynb, manipulation/make_drake_compatible_model.py
See https://github.shared-services.aws.tri.global/robotics/anzu/issues/13763
Resolves #417 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/426)
=> Adds a franka kitchen example

book/robot/menagerie.ipynb, manipulation/make_drake_compatible_model.py
Resolves #428, and wow the robots look so much better.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/430)
=> Add mujoco-specified materials to mtl when creating objs

book/robot/menagerie.ipynb, manipulation/make_drake_compatible_model.py
Workaround for https://github.com/RobotLocomotion/drake/issues/22488.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/432)
=>  Support refquat and refpos for mujoco meshes

.github/workflows/main.yml, manipulation/make_drake_compatible_model.py, manipulation/remotes.py
updated to noble instead of jammy
Resolves #461.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/464)
=> Re-enable pip-core CI

manipulation/BUILD.bazel
Addressed [this comment](https://github.com/RussTedrake/manipulation/pull/474#pullrequestreview-3173730351).
The dependencies should certainly be for the module, not just the tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/479)
=> Move optional deps from letter_generation tests to module

book/intro/exercises/02_drake_systems_fundamentals.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/486)
=> Typo: Change angular velocity to angle

.github/workflows/main.yml
for testing solutions from forks on CI, with a whitelist required for approval.
cc @bernhardpg
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/493)
=> Use pull request target workflow

book/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/527)
=> Update year to 2025

pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/528)
=> Update version number to 10.1

pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/529)
=> Update version number to 10.1.2

pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/535)
=> Bump version number to 10.6
