RussTedrake/manipulation

manipulation/exercises/pick/test_differential_ik.py
Turns out some people wrote the constraint in the unit of velocity instead of position, and that was enough to screw with the numerics of the solver and break the tight tolerance on the testing code. 
This fix relaxes the tolerance so that both answers are accepted (Still pretty low)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/37)
=> fix tolerance on diffik test

manipulation/exercises/pick/test_robot_painter.py
Fix on the autograder of robot painter. When comparing two same trajectories, one constructed from RotationMatrix and the other constructed from 3x3 NumPy array, the pydrake.trajectories.PiecewisePolynomial.isApprox returns False.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/38)
=> Pick and place/painter test

manipulation/exercises/pose/test_icp.py, manipulation/exercises/pose/test_ransac.py
@mfeng9 for the record, here are the bugs that were in the previous test:
- Students would sometimes see tests succeeding and failing at random for ransac and icp. RANSAC is really random, so I've added `np.random.seed` to make the test more deterministic (always a good practice for testing that includes random)
- The ICP had a more interesting testing bug. If students forget to handle improper rotations, the following happens:
- since the test cases written for `least_squares_transform` are based on proper rigid transforms, it never checks for handling of improper rotations. 
- but this does matter for `icp` since there correspondences are not one-to-one and improper transforms occur. So they would get full score on `least_squares_transforms` but get points off for `icp`.  
- There are a …
=> Chapter 4 Test Fixes

scripts/setup/setup_manipulation_colab.py
Scope nested `setup_drake` to imported module; otherwise, looks
like confusing recursion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/82)
=> setup_manipulation_colab: Remove hack for continuous builds

exercises/trajectories/door_opening.ipynb
Gradescope is an instance of `not running_as_notebook`, so it won't simulate the trajectory in full.
The test times out, but it's not clear how to have a flag of "not running as notebook but running in gradescope".
Currently my solution is to have the students manually uncomment the line that simulates for 11 seconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/103)
=> change simulation duration

manipulation/exercises/grader.py
This is a hack to filter out lines with "clearOutput" when parsing the notebook. Currently, "clearOutput" is not a recognized type by the notebook parser and thus fails on these lines. This hack is a particularly inelegant solution, but would work as a temporary patch for Homework 10.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/185)
=> Temporary Resolution to clearOutput Error

manipulation/exercises/deep_perception/test_contrastive.py
See https://piazza.com/class/l6s8p2f23ij7bz/post/404.
Since doc string says feature encoder can take in arbitrary batch size, I am correcting it here
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/215)
=> fix corner case in 7.1 test

exercises/pose/pose_estimation_icp.ipynb
PointCloud requires second argument to be of type Fields. Otherwise it raises TypeError:
`TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
1. pydrake.perception.PointCloud(new_size: int = 0, fields: pydrake.perception.Fields = Fields(base_fields=2))
2. pydrake.perception.PointCloud(other: pydrake.perception.PointCloud)
`
Instantiate Fields from BaseFields for rgb visualization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/russtedrake/manipulation/228)
=> Pass BaseFields as Fields object

robot.html
The image for the ABB Yumi robot is currently pointing to a [broken link](https://www07.abb.com/api/ir/getimage/36fb710b-54e0-4e53-8383-aacde553ec56/1). I've updated the link to [this](https://webshop.robotics.abb.com/media/catalog/product/d/u/dual_arm_yumi_14000_main.jpg), which matches the previous image (as seen from the [wayback machine](https://web.archive.org/web/20190415034543/https://www07.abb.com/api/ir/getimage/36fb710b-54e0-4e53-8383-aacde553ec56/1)).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/236)
=> Fix broken image link for ABB Yumi.

robot.html
The link currently points to the old notebook (that uses manipulation station). This updates it to point to the hardware station notebook.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/245)
=> Fix deepnote link for exercise 2.2.

manipulation/exercises/clutter/test_grasp_candidate.py
Allow Darboux frames that are rotated by 180 degrees about the y-axis, since they're also correct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/257)
=> Fix for Darboux Frame Autograder

manipulation/models/pr2_collision_fixed.urdf
Two of the PR2 transmissions were commented out in the urdf, making inverse dynamics controller unhappy. This fixes it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/270)
=> PR2 Transmission Fix

poetry.lock, pyproject.toml
Softening this dependency makes dependency management when `manipulation` is one of the dependencies a lot easier. Moreover, Drake won't break anything.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/299)
=> Soften Drake dependency

README.md, manipulation/models/spot/spot_with_arm_and_floating_base_actuators.scenario.yaml, manipulation/station.py, pyproject.toml
- Currently, the PID gains of the `InverseDynamicsController` are fixed to a certain default (kp=100, ki=1, kd=20).
- Taking the PID gains as parameters is marked as a TODO item.
- This PR implements taking parameters of the `InverseDynamicsDriver` as parameters.
- This is specified by the user as a mapping from the names of the actuator joins to the PID gains, like so:
```yaml
model_drivers:
spot: !InverseDynamicsDriver
gains:
arm_sh0: {kp: 1000, ki: 10, kd: 50}
arm_sh1: {kp: 1000, ki: 10, kd: 50}
arm_el0: {kp: 1000, ki: 10, kd: 50}
arm_el1: {kp: 1000, ki: 10, kd: 50}
arm_wr0: {kp: 1000, ki: 10, kd: 50}
arm_wr1: {kp: 1000, ki: 10, kd: 50}
arm_f1x: {kp: 3000, ki: 20, kd: 50}
```
The user is allowed to set the gains of any _subset_ of actuators. Any unspecified actuators will use the …
=> Take gains for `InverseDynamicsDriver` as parameters

manipulation/station.py, pyproject.toml
Fixes #316 
- Create the controller plant for the `IiwaDriver` by reusing the user-provided scenario, instead of creating a custom iiwa (hardcoded to iiwa7) and the WSG schunk.
- This is enabled by being able to freeze child instances i.e. removing non-weld joints in the child instance and replacing them with weld joints. This is in-turn made possible by this recently landed PR: (https://github.com/RobotLocomotion/drake/pull/21397)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/317)
=> `IiwaDriver`: Create controller MBP from scenario file

manipulation/BUILD.bazel, manipulation/directives_tree.py, manipulation/station.py, manipulation/test/test_directives_tree.py
Fixes #322 
- **Nodes:** are defined by _(1)_ model instances and _(2)_ added frames.
- **Edges:** are defined by _(1)_ `add_weld` and _(2)_ `add_frame` directives.
- Finding paths from the root ("world" frame) to a given set of robot instances. The use case is to find the minimal set of directives that supports the given robot instances.
- Finding paths from given robot instances to leaves. The use case is to find child model instances that are welded to the robots (as well as accompanying directives), which is in-turn used to lock the childrens' joints and add their directives to a controller plant.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/323)
=> Support `add_frame` directives when adding frozen children

manipulation/BUILD.bazel, manipulation/station.py, manipulation/test/test_hardware_station_interface.py, pyproject.toml
Slack thread: https://drakedevelopers.slack.com/archives/C2CK4CWE7/p1720146312718089
When using `MakeHardwareStation(meshcat, hardware=True)` , `_MakeHardwareStationInterface(meshcat)` completely ignores its meschat. However, a strong use-case when running real robot hardware is to run Meshcat and visualize robot positions.
It seems that a (partial) solution was previously implemented, but was commented out.
**Philosophy:** When the user passes a meshcat instance when running on real hardware, we assume that the user wants to visualize robot positions using this instance. In this case, the relevant systems are added to the station and wired appropriately (see below). When `meshcat=None`, these are not added.
The following system diagrams were generated from …
=> Visualize robot positions in HardwareStationInterface

book/pose.html
model points should be expressed relative to pose of object
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/355)
=> fix 4.5 world/object frames

book/clutter.html, book/pose.html
- The size of the new image for the modified 4.10 problem was too small. I verified this new sizing locally first and it is now a lot better.
- Updated 5.2 problem description.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/360)
=> fixed scaling of image for 4.10

manipulation/directives_tree.py, manipulation/station.py, manipulation/test/test_directives_tree.py
The 'return' statement ignored all but the first model instance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/370)
=> Fix GetWeldToWorldDirectives for more than one model instances

manipulation/exercises/segmentation/test_segmentation_and_grasp.py
For some reason, the model prediction with the same weights is different on deepnote than on my local computer. We need to increase the tolerance to account for this...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/380)
=> Increase the segmentation_and_grasp test tolerance

manipulation/create_sdf_from_mesh.py, manipulation/meshcat_utils.py, manipulation/scenarios.py, manipulation/station.py, manipulation/systems.py, manipulation/utils.py
Currently, many arguments are annotated as type `Type` (e.g. `Meshcat`) while their default value is set to `None`. This "implicit optional" convention, which was acceptable in the past, is now discouraged by PEP-484 [[1](https://peps.python.org/pep-0484/#union-types)]. It causes my editor to show "unreachable code" warnings since it assumes these arguments cannot be None.
This PR fixes the type annotation from `Type` to `Type | None`.
There is an older way to denote `typing.Union[Type, None]`, which is `typing.Optional[Type]`. `Type | None` was introduced in PEP-604. Both are valid. There is no precedent in the manipulation repo, while both have been used in Drake [[2](https://github.com/search?q=repo%3ARobotLocomotion%2Fdrake+%22typing.Optional%22&type=code), …
=> Add "| None" type annotation for args that can be `None`

pyproject.toml
I think changing the list format for the `all` extras improves readability when viewing from github or IDE. Let me know if you disagree :)
The comment whitespace changes are for consistency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/403)
=> Clean up pyproject.toml

book/robot/BUILD.bazel, book/robot/inspector.ipynb, book/robot/menagerie.ipynb, manipulation/make_drake_compatible_model.py, manipulation/test/test_make_drake_compatible_model.py, manipulation/utils.py
It works for a handful of the cases I've tried, but I'm sure there will be more improvements coming. I've not added additional tests, since I'm mostly checking things visually for now. I will add tests that at least check the texture path in the mtl file soon.
For instance, I've found that it works for Cassie's legs, but not yet for the pelvis:
Towards [#419](https://github.com/RussTedrake/manipulation/issues/419)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/423)
=> Initial implementation of mujoco texture support

.github/workflows/main.yml
The isort lint CI reported errors that it caught but didn't make the CI fail. This didn't happen in this repo, as we were good at using `pre-commit`. However, I discovered this in a different repo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/448)
=> Fix isort lint CI

.github/workflows/main.yml
This PR adds a check on the workflow, and skips the workflow if it is triggered by a `pull_request` from a forked repository (these will always fail, as the workflows triggered by `pull_request` event runs the forked code and does not have access to the repo secrets and can't checkout the notebook solutions). As a result, only the workflows triggered by (approved) `pull_request_target` events run for forked PRs, which is what we want.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RussTedrake/manipulation/495)
=> Only run pull_request_target for forked PRs
